### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeName' of undefined

### ISSUE THREAD

**Issue by NormannTan** [atom/notifications#135] opened 2016-12-08 03:29 UTC
[Enter steps to reproduce below:]

1. script > configure script
2. command: python3
3. run

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.65.1

### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:81:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:33:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at ScriptOptionsView.run (/Users/normantan/.atom/packages/script/lib/script-options-view.js:196:19)
    at HTMLButtonElement.<anonymous> (/Users/normantan/.atom/packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/Users/normantan/.atom/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Users/normantan/.atom/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:29.3.0 application:open (atom-pane.pane.active)
     -3:17.4.0 symbols-view:toggle-project-symbols (atom-text-editor.editor.is-focused)
     -3:14.3.0 script:run-with-profile (atom-text-editor.editor.is-focused)
     -3:08.4.0 script:run-options (atom-text-editor.editor.is-focused)
     -2:18.7.0 settings-view:open (a.btn-issue.btn.btn-error)
     -1:30.7.0 core:save (atom-text-editor.editor.is-focused)
  4x -1:29.1.0 script:run (atom-text-editor.editor.is-focused)
     -1:21.4.0 grammar-selector:show (atom-text-editor.editor)
     -1:03.6.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -0:05.1.0 script:run-options (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.8.20 (active)
linter, v1.11.18 (active)
linter-flake8, v2.1.3 (active)
minimap, v4.25.7 (active)
pigments, v0.38.0 (active)
script, v3.12.0 (active)
spacegray-atom-dark-syntax, v1.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by unixforever** [comment] 2016-12-20 14:20
I'm having an same issue.

**Comment by ammar1y** [comment] 2016-12-20 15:53
I have the same issue too.

**Comment by tipra34** [comment] 2016-12-22 06:06
same here.

**Comment by cailmdaley** [comment] 2016-12-23 17:18
This is also happening to me.

**Comment by WASSIMATHIMNI** [comment] 2016-12-24 19:21
+1

**Comment by kimshako** [comment] 2016-12-26 20:35
+1

**Comment by 50Wliu** [comment] 2016-12-30 23:03
Can everyone who is running into this please list reproduction steps please?

**Comment by blokeley** [comment] 2017-01-02 15:39
It happens for me when I use Script: Run Options and put "-h" in Command Arguments or Program Arguments and press Run for a Python 3 file

Versions: 
Atom 1.12.6
Script 3.12.0
Windows 10 Anniversary Edition

**Comment by mondlos** [comment] 2017-01-03 08:56
Same thing happens to me. 
I have a new clean Atom installation except of PlatformIO and the Script Plugin. I did Packages - Script - Configure Script and added python3 as a command.
I'm using the newest version of Atom and Script on Windows 10. Pls Fix.

**Comment by yeoldelloyd** [comment] 2017-01-03 11:50
+1

**Comment by zazazack** [comment] 2017-01-06 16:53
+1

**Comment by danielxji6** [comment] 2017-01-07 22:16
+1

**Comment by ookimi** [comment] 2017-01-09 01:02
Same here with Ubuntu 16.04

**Comment by 50Wliu** [comment] 2017-01-09 03:09
/cc @lgeiger: it looks like this started happening right after the 3.12.0 release, which is when the Coffeescript -> ES6 conversion was released.  It looks like one of your commands (specifically, the Python one) is missing a target.

Going to tentatively mark this as wontfix since targets are required.

**Comment by lgeiger** [comment] 2017-01-09 12:48
@50Wliu Thanks for pinging me. You're right, the command is missing a target.

I made a PR to fix it: https://github.com/rgbkrk/atom-script/pull/1209

**Comment by lgeiger** [comment] 2017-01-10 13:18
This issue is fixed in Atom Script `v3.14.0`

**Closed** 2017-01-10 16:07 UTC
Labels: more-information-needed, uncaught-exception, wontfix

**Comment by antoine-wordofclick** [comment] 2017-03-31 09:27
I'm getting the same error :

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.4
**Thrown From**: [notifications](https://github.com/atom/notifications) package 0.66.2


### Stack Trace

Uncaught TypeError: Cannot read property 'nodeName' of undefined

```
At /Users/name/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/command-logger.js:81

TypeError: Cannot read property 'nodeName' of undefined
    at CommandLogger.module.exports.CommandLogger.logCommand (/app.asar/node_modules/notifications/lib/command-logger.js:81:38)
    at /app.asar/node_modules/notifications/lib/command-logger.js:33:24
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at ScriptOptionsView.run (/packages/script/lib/script-options-view.js:196:19)
    at /packages/script/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -9:52.3.0 script:run-options (input.hidden-input)
  2x -8:16.6.0 window:toggle-dev-tools (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:13 script:run-options (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
an-old-hope-syntax 0.5.0 
atom-beautify 0.29.13 
autoclose-html 0.23.0 
autocomplete-elixir 1.5.14 
babel-react-syntax 1.2.0 
emmet 2.4.3 
language-babel 2.48.5 
language-blade 0.26.2 
language-elixir 0.16.0 
linter 1.11.18 
linter-eslint 8.0.0 
react 0.16.1 
react-native-snippets 0.3.0 
script 3.12.0 
seti-icons 1.3.4 
```

**Comment by 50Wliu** [comment] 2017-03-31 14:36
@antoine-wordofclick Update script.

**Comment by simonmeusel** [comment] 2017-05-09 18:12
+1

**Comment by macpie** [comment] 2017-08-10 01:08
This seem to happen when there is not tab open with or without package `script` installed.

**Comment by stvkoch** [comment] 2017-09-27 14:33
This happens to me when I move the next tab using keybinding from vim-mode-plus "g t", trying to go a tab with a "Search Result"

I hope to clarify

**Comment by zyplok** [comment] 2017-10-11 00:33
**//same**
